plugins {
    id 'java'
}

group 'ru.netology'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
    testImplementation 'com.codeborne:selenide:6.19.1'
    testImplementation 'mysql:mysql-connector-java:8.0.33'
    testImplementation 'commons-dbutils:commons-dbutils:1.7'
    testCompileOnly 'org.projectlombok:lombok:1.18.34'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.34'

}

test {
    useJUnitPlatform()
    systemProperty 'selenide.headless', System.getProperty('selenide.headless', 'true')

    // prefs передаются строкой key=value;key2=value2
    // выключаем менеджер паролей/сервис учетных данных (часто ломает CI)
    systemProperty 'chromeoptions.prefs', System.getProperty(
            'chromeoptions.prefs',
            'credentials_enable_service=false;profile.password_manager_enabled=false'
    )
}
